# SPDX-License-Identifier: GPL-2.0
#
# Makefile for samsung regulator drivers.
#

obj-$(CONFIG_REGULATOR_S2MPS25)		+= s2mps25-regulator.o
s2mps25-regulator-$(CONFIG_REGULATOR_S2MPS25)	+= s2mps25_regulator.o s2mps25_powermeter.o
obj-$(CONFIG_REGULATOR_S2MPS26)		+= s2mps26-regulator.o
s2mps26-regulator-$(CONFIG_REGULATOR_S2MPS26)	+= s2mps26_regulator.o s2mps26_powermeter.o
obj-$(CONFIG_REGULATOR_S2MPM07) += s2mpm07_regulator.o
obj-$(CONFIG_REGULATOR_S2MPB02) += s2mpb02-regulator.o
obj-$(CONFIG_REGULATOR_S2MPB03) += s2mpb03.o
obj-$(CONFIG_REGULATOR_S2DOS07)		+= s2dos07-regulator.o
s2dos07-regulator-$(CONFIG_REGULATOR_S2DOS07)	+= s2dos07.o
obj-$(CONFIG_REGULATOR_S2MPB06) += s2mpb06-regulator.o
obj-$(CONFIG_REGULATOR_S2DPS01) += s2dps01.o
obj-$(CONFIG_REGULATOR_S2MPS27)	+= s2mps27_regulator.o
obj-$(CONFIG_REGULATOR_S2MPS28)	+= s2mps28_regulator.o
obj-$(CONFIG_REGULATOR_S2MPU15_8845) += s2mpu15_regulator_8845.o
obj-$(CONFIG_REGULATOR_S2MPU16_8845) += s2mpu16_regulator_8845.o
