# SPDX-License-Identifier: GPL-2.0
# SAMSUNG pmic pinmux support

obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPS26) += pinctrl-samsung-s2mps26.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPM07) += pinctrl-samsung-s2mpm07.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPS28) += s2mps28_pinctrl.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU15_8845) += s2mpu15_pinctrl_8845.o
obj-$(CONFIG_PINCTRL_SAMSUNG_S2MPU16_8845) += s2mpu16_pinctrl_8845.o
